resources:
  - { type: kpr, path: src/main/resources/com/slb/vertigo/poc/business/application.kpr}
mdaConfig:
  projectPackageName: com.slb.vertigo.poc
  targetGenDir : src/main/
  properties:
    vertigo.domain.java: true
    vertigo.domain.java.generateDtResources: false
    vertigo.domain.sql: true
    vertigo.domain.sql.targetSubDir: javagen/sqlgen
    vertigo.domain.sql.baseCible: H2
    vertigo.domain.sql.generateDrop: true
    vertigo.domain.sql.generateMasterData: true
    vertigo.task: true